import streamlit as st
import pandas as pd
import plotly.graph_objects as go

def render_dashboard(data: dict):
    """
    Renders the premium analytics dashboard including KPIs formatted in Billions ($B),
    an interactive Plotly chart with quarterly detail and vertical news event indicators,
    the AI-verified report summary, and Korean translated news sorted chronologically in yearly tabs.
    """
    if not data:
        st.warning("표시할 분석 데이터가 없습니다.")
        return

    company_profile = data.get("company_profile", "")
    financials = data.get("financials", {})
    financial_summary = data.get("financial_summary", {})
    trends = data.get("trends", [])
    chart_events = data.get("chart_events", [])

    ticker = financials.get("ticker", "UNKNOWN")
    dates = financials.get("dates", [])
    revenue = financials.get("revenue", [])
    net_income = financials.get("net_income", [])

    # 1. Company Profile Header
    st.markdown(f"## 📊 {ticker} 기업 종합 분석 리포트")
    if company_profile:
        # Display the Korean profile generated by Gemini in a clean highlighted container
        st.info(company_profile)

    # 2. KPI Scorecards in Billions ($B)
    if revenue and net_income:
        latest_rev = revenue[-1]
        latest_ni = net_income[-1]
        
        col1, col2 = st.columns(2)
        with col1:
            if latest_rev is not None:
                rev_str = f"${latest_rev / 1e9:,.2f} B"
            else:
                rev_str = "N/A"
            st.metric(label="최근 분기 매출액 (Revenue)", value=rev_str)
        with col2:
            if latest_ni is not None:
                ni_str = f"${latest_ni / 1e9:,.2f} B"
            else:
                ni_str = "N/A"
            st.metric(label="최근 분기 순이익 (Net Income)", value=ni_str)

    # 3. Interactive Plotly quarterly chart with news event indicators
    st.subheader("📈 3개년 분기별 재무 실적 및 핵심 이슈 연동")
    if dates:
        fig = go.Figure()
        
        # Convert values to Billions ($B) for cleaner plot scale
        revenue_b = [r / 1e9 if r is not None else None for r in revenue]
        net_income_b = [n / 1e9 if n is not None else None for n in net_income]
        
        # Revenue trace
        fig.add_trace(go.Scatter(
            x=dates,
            y=revenue_b,
            mode='lines+markers',
            name='매출액 (Revenue, $B)',
            line=dict(color='#1f77b4', width=3),
            marker=dict(size=7),
            connectgaps=False # Gap handling (does not connect N/A points)
        ))
        
        # Net Income trace
        fig.add_trace(go.Scatter(
            x=dates,
            y=net_income_b,
            mode='lines+markers',
            name='순이익 (Net Income, $B)',
            line=dict(color='#ff7f0e', width=3),
            marker=dict(size=7),
            connectgaps=False # Gap handling (does not connect N/A points)
        ))

        # Add vertical line overlays & hover annotations for core events
        for ev in chart_events:
            ev_date = ev.get("date")
            ev_title = ev.get("title")
            ev_summary = ev.get("summary")
            sentiment = ev.get("sentiment")
            
            # Sentiment coloring for dots and lines
            if sentiment == "Good":
                color = "#1f77b4" # Blue
                emoji = "🔵"
            elif sentiment == "Bad":
                color = "#d62728" # Red
                emoji = "🔴"
            else:
                color = "#7f7f7f" # Grey
                emoji = "🟢"
                
            # Add vertical dotted line
            fig.add_vline(
                x=ev_date,
                line_width=2,
                line_dash="dot",
                line_color=color
            )
            
            # Hoverable annotation marker at the top panel of chart
            fig.add_annotation(
                x=ev_date,
                y=1.05,
                yref="paper",
                text=f"{emoji} {ev_date[5:7]}월 이슈",
                showarrow=False,
                font=dict(size=10, color="white"),
                bgcolor=color,
                bordercolor=color,
                borderwidth=2,
                borderpad=4,
                # Hover tooltip format containing full translated summary of event
                hovertext=f"<b>{ev_title}</b><br><br>{ev_summary}"
            )

        fig.update_layout(
            xaxis=dict(title="공시 종료일 (Period End Date)", type='date'),
            yaxis=dict(title="금액 (십억 달러, $B)"),
            legend=dict(orientation="h", yanchor="bottom", y=1.08, xanchor="right", x=1),
            margin=dict(l=40, r=40, t=60, b=40),
            hovermode="x unified",
            template="plotly_white"
        )
        st.plotly_chart(fig, use_container_width=True)
        
        # 3.1 Annual Summary Table
        st.markdown("##### 📋 연도별 누적 실적 요약 (매출액 / 순이익 / 순이익률)")
        yearly_summary = {}
        for d, rev, ni in zip(dates, revenue, net_income):
            year = d[:4]
            if year not in yearly_summary:
                yearly_summary[year] = {"revenue": 0.0, "net_income": 0.0, "has_rev": False, "has_ni": False}
            if rev is not None:
                yearly_summary[year]["revenue"] += rev
                yearly_summary[year]["has_rev"] = True
            if ni is not None:
                yearly_summary[year]["net_income"] += ni
                yearly_summary[year]["has_ni"] = True
                
        table_rows = []
        for y in sorted(yearly_summary.keys()):
            y_info = yearly_summary[y]
            rev_val = y_info["revenue"]
            ni_val = y_info["net_income"]
            
            rev_fmt = f"${rev_val / 1e9:,.2f} B" if y_info["has_rev"] else "N/A"
            ni_fmt = f"${ni_val / 1e9:,.2f} B" if y_info["has_ni"] else "N/A"
            
            if y_info["has_rev"] and y_info["has_ni"] and rev_val > 0:
                margin = f"{(ni_val / rev_val) * 100:.2f}%"
            else:
                margin = "N/A"
                
            table_rows.append({
                "회계 연도": f"{y}년",
                "누적 매출액 (Revenue)": rev_fmt,
                "누적 순이익 (Net Income)": ni_fmt,
                "순이익률 (Net Margin)": margin
            })
            
        if table_rows:
            df_summary = pd.DataFrame(table_rows)
            # Render a clean, standard Streamlit table
            st.dataframe(df_summary, use_container_width=True, hide_index=True)
    else:
        st.info("재무 제표 데이터가 제공되지 않았습니다.")

    # 4. AI-Verified Financial Summary Table
    st.subheader("🛡️ AI 실시간 검증 재무 요약 (연도별)")
    if financial_summary and financial_summary.get("summary"):
        # Render the markdown table generated by Gemini/fallback directly
        st.markdown(financial_summary["summary"])
    else:
        st.warning("재무 요약이 검증을 통과하지 못해 배제되었거나 존재하지 않습니다.")

    # 5. News Trends (Yearly Tab Layout with 2-column Good/Bad contrast)
    st.subheader("📰 주요 이슈 및 뉴스 분석")
    st.caption("뉴스는 시간 내림차순(최신순)으로 정렬되어 있으며, 중립 의견을 제외하고 호재(Good)와 악재(Bad)만 선명하게 비교합니다.")
    
    # Filter trends into distinct calendar years (Good and Bad only)
    trends_good_bad = [t for t in trends if t.get("sentiment") in ["Good", "Bad"]]
    trends_2025 = [t for t in trends_good_bad if t.get("year", 0) >= 2025]
    trends_2024 = [t for t in trends_good_bad if t.get("year", 0) == 2024]
    trends_2023 = [t for t in trends_good_bad if t.get("year", 0) == 2023]
    
    # Create clean Tabs for time classification, starting with 'All Years'
    tab_all, tab_2025, tab_2024, tab_2023 = st.tabs([
        "📋 전체 연도 보기",
        "📅 올해 (2025년 ~)",
        "📅 작년 (2024년)",
        "📅 재작년 (2023년)"
    ])
    
    def render_news_column(news_list, header_emoji, title_color, header_text):
        st.markdown(f"##### {header_emoji} {header_text} ({len(news_list)})")
        if not news_list:
            st.caption("이 분류에 해당하는 직접적 이슈가 없습니다.")
            return

        for item in news_list:
            card_html = f"""
            <div style="
                border: 1px solid #eef2f3;
                border-radius: 8px;
                padding: 12px;
                margin-bottom: 8px;
                background-color: #fafbfc;
                box-shadow: 1px 1px 4px rgba(0,0,0,0.02);
            ">
                <div style="display: flex; justify-content: space-between; font-size: 0.78em; color: #777; margin-bottom: 4px;">
                    <span><b>{item.get('quarter', 'N/A')}</b> ({item.get('date', 'N/A')})</span>
                    <span>출처: {item.get('source')}</span>
                </div>
                <h5 style="margin: 4px 0 8px 0; color: {title_color}; line-height: 1.35;">{item.get('title')}</h5>
                <p style="font-size: 0.88em; color: #333; line-height: 1.45; margin-bottom: 6px;">
                    {item.get('summary')}
                </p>
            </div>
            """
            st.markdown(card_html, unsafe_allow_html=True)
            st.link_button(
                f"🔗 기사 원문 보기", 
                item.get('url', '#'), 
                help=f"클릭 시 {item.get('source')} 원본 기사 웹페이지로 새 탭에서 이동합니다.",
                use_container_width=True
            )
            st.write("")

    def render_year_tab(news_items):
        if not news_items:
            st.info("해당 기간의 수집된 직접적 이슈 뉴스가 없습니다.")
            return
            
        good_news = [t for t in news_items if t.get("sentiment") == "Good"]
        bad_news = [t for t in news_items if t.get("sentiment") == "Bad"]
        
        # 2-column layout to contrast Good vs Bad aggressively (no Neutral column)
        col_good, col_bad = st.columns(2)
        with col_good:
            render_news_column(good_news, "🔵", "#1f77b4", "호재 (Good)")
        with col_bad:
            render_news_column(bad_news, "🔴", "#d62728", "악재 (Bad)")

    with tab_all:
        render_year_tab(trends_good_bad)

    with tab_2025:
        render_year_tab(trends_2025)

    with tab_2024:
        render_year_tab(trends_2024)

    with tab_2023:
        render_year_tab(trends_2023)
